os:
    - linux


install:
    # Because Travis can't somehow have a gcc or cmake version from this decade installed by default >.>
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz --no-check-certificate; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir cmake-dist; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xzf cmake-3.4.0-Linux-x86_64.tar.gz -C cmake-dist --strip-components=1; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=$PWD/cmake-dist/bin:$PATH; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=$PATH:/opt/local/bin:/opt/local/sbin:/usr/bin/c++:/usr/bin/make; fi

    - ./download_cpp_dependencies.sh
    - ./build_cpp.sh
    - ./build_tests_cpp.sh

script:
    - cd build_tests
    - ./Matrix_Tests

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
